### ISSUE TITLE
Duplicate search result

### ISSUE THREAD

**Issue by mneise** [fgeller/rad#65]
When searching for the Clojure function `finally`, it was shown twice (screenshot attached). I am not able to reproduce this problem every time and it only occurred twice so far.

![img_2015-10-26 15 16 11](https://cloud.githubusercontent.com/assets/881353/10719830/eb77296c-7bf4-11e5-9774-e9023fc6153f.jpg)

**Comment by fgeller** [comment]
Hard to reproduce but I think 79922b5 fixes this. Let me know if it happens again
