### ISSUE TITLE
Local packs

### ISSUE THREAD

**Issue by mknecht** [fgeller/rad#81]
Is there a way to dump manuals / docs in a local folder and have them included (semi-)automatically? There's lots of tiny docs or docs of tools that are useful to probably five other ppl on the planet, and I'd like to be able to search them, too.

**Comment by fgeller** [comment]
The default process for installing packs is currently like this:

* `sad` asks a running `sap` instance for available (zipped) packs and checks a configurable folder `sad-packs` for installed packs. By default the `sad-packs` folder is `$HOME/.rad/sad-packs`.
* When installing a pack, the zip is downloaded from the `sap` instance and unpacked into the local `sad-packs` folder
* The contents of the `sad-packs` folder are loaded on start up and are what you can search by default

Now, you could either produce a zipped pack and serve it via a local `sap` instance, or just create the pack folder structure in your local `sad-packs` folder. In order for rad to pick new packs up you need to follow the structure outlined in the main README: basically a sub-folder with a `pack.json` (pack metadata) and a `data.json` (the index)  and then a sub-folder with the HTML contents. The easiest way to produce these is via `pad` at the moment. e.g., if you want to include javadocs or python docs, `pad` should be able to help you out. Or have a look at installed packs to get examples for the structure. 

Let me know if I can help out somehow.

**Comment by mknecht** [comment]
Fun, I'll go for the local approach folder approach, as I don't need the serving just yet. :) Will ping back, if I run into problems. Thanks!
